title: Stepp Lab Calculator for Assessing Intelligibility

navbar-links:
  Tool for Intelligibility Assessment: "index"
  Stepp Lab Homepage: "https://stepplab.com"

avatar: "/assets/logo.png"
round-avatar: false
#title-img: "/assests/logo.png"

social-network-links:
  email: "stepplab@gmail.com"
  facebook: stepplab
  github: stepplab
  twitter: stepplab
  youtube: "@stepplab"
  linkedin: stepplab
  instagram: stepplab

share-links-active:
  email: true
  facebook: true
  github: true
  twitter: true
  youtube: true
  linkedin: true
  instagram: true

# title-on-all-pages: true
# excerpt_length: 50
# feed_show_excerpt: true
# feed_show_tags: true
# post_search: true
# edit_page_button: true
# navbar-var-length: false

# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# navbar-col: "#EAEAEA"
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# footer-col: "#EAEAEA"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

gtag: "G-2YPGH9Y63J"
date_format: "%B %-d, %Y"
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme


